inherit_from: /usr/local/Homebrew/Library/.rubocop.yml

Homebrew/ShellCommands:
  Enabled: false

Layout/LineLength:
  Enabled: false
Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

Style/Documentation:
  Enabled: false
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
Style/NestedModifier:
  Enabled: false
Style/SoleNestedConditional:
  AllowModifier: true
Style/SymbolArray:
  EnforcedStyle: percent
Style/TernaryParentheses:
  EnforcedStyle: require_no_parentheses
