name: CI
on:
  push:
    branches: [main]
    paths: '**.rb'
  pull_request:
    paths: '**.rb'

jobs:
  CI:
    runs-on: macos-latest
    steps:
    - name: ${{github.workflow}}
      uses: danielbayley/homebrew-pipeline@main
      env:
        ACTIONS_STEP_DEBUG: ${{secrets.ACTIONS_STEP_DEBUG}}
